# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Landmarks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Landmarks
  pod 'AWSMobileClient', '~> 2.12.1'    # Required dependency
  pod 'AWSAuthUI', '~> 2.12.1'          # Optional dependency required to use drop-in UI
  pod 'AWSUserPoolsSignIn', '~> 2.12.1' # Optional dependency required to use drop-in UI

end
